name: js:pre-release

on:
  push:
    tags: '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-pre-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Get the Git tag name
      id: get-tag-name
      run: echo ::set-output name=tag-name::${GITHUB_REF/refs\/tags\//}
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get-tag-name.outputs.tag-name }}
        release_name: v${{ steps.get-tag-name.outputs.tag-name }}
        body: |-
          "djt-promised-require" release v${{ steps.get-tag-name.outputs.tag-name }}
        prerelease: true
