name: js:test

on:
  push:
    branches-ignore: '*/*'

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1.4.4
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        npm run install-clean
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: javascript
        queries: security-extended
    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v1

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x ]

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        npm run install-clean
    - name: Execute linter for static code analysis
      run: |-
        node node_modules/eslint/bin/eslint.js --quiet ./src/
    - name: Execute tests
      run: npm test
    - name: Execute permissive linter
      continue-on-error: true
      run: |-
        node node_modules/eslint/bin/eslint.js ./src/
